version: '3.1'

services:
 okta-feed-me-well-db:
   container_name: okta-feed-me-well-db
   image: mysql
   command: --default-authentication-plugin=mysql_native_password
   restart: always
   ports:
     - 3389:3306
   environment:
     MYSQL_ROOT_PASSWORD: example
     MYSQL_DATABASE: okta-feed-me-well-db
     MYSQL_USER: user
     MYSQL_PASSWORD: password