version: '3'

services:
  app:
    container_name: node-app
    build: ./app
    ports:
      - "3000:3000"
    links:
      - mysql-dev
    depends_on:
      - mysql-dev
    restart: always
    command: npm start


  mysql-dev:
    container_name: mysql-dev
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    ports:
      - "3306:3306"
